config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :shops do
    resources :drinks
    resources :shop_comments
  end

  resources :locations

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tags
  has_many :shops, through: :tags
end

app/models/drink.rb
class Drink < ApplicationRecord
  belongs_to :shop
  validates :name, presence: true
end

app/models/location.rb
class Location < ApplicationRecord
  has_and_belongs_to_many :shops
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :drinks, dependent: :destroy
  has_many :shop_comments, dependent: :destroy
  has_many :tags, dependent: :destroy
  has_many :categories, through: :tags
  validates :name, presence: true

end

app/models/shop_comment.rb
class ShopComment < ApplicationRecord
  belongs_to :shop
  validates :heading, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :shop
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  rescue_from ActiveRecord::RecordNotFound, with: :couldnt_find_record

  private
  def couldnt_find_record
    redirect_to root_url, notice: "That record doesn't exist!"
  end

end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  # before_action :authenticate_user!

  def show
    @drink = Drink.find(params[:id])
    @placeholder_drink = "/images/drinks/default.jpg"
  end

  def new
    @shop = Shop.find(params[:shop_id])
    @drink = @shop.drinks.new
  end

  def edit
    @shop = Shop.find(params[:shop_id])
    @drink = Drink.find(params[:id])
  end

  def create
    @shop = Shop.find(params[:shop_id])
    @drink = @shop.drinks.create(drink_params)

    if @drink.save
      redirect_to shop_path(@shop), notice: "Sweet. You added some mo' coffee."
    else
      render 'new'
    end
  end

  def update
    @shop = Shop.find(params[:shop_id])
    @drink = Drink.find(params[:id])

    if @drink.update(drink_params)
      redirect_to shop_drink_path(@shop, @drink), notice: "Sweet, you updated a drink."
    else
      render 'edit'
    end
  end

  def destroy
    @drink = Drink.find(params[:id])
    @drink.destroy
    redirect_to shop_path(@drink.shop), alert: "Oh nos, you deleted some coffees!"
  end

  private
    def drink_params
      params.require(:drink).permit(:shop_id, :img_url, :name, :kind_of_drink, :roast, :flavor, :thoughts)
    end

end

app/controllers/shop_comments_controller.rb
class ShopCommentsController < ApplicationController
  # before_action :authenticate_user!

  def show
    @shop_comment = ShopComment.find(params[:id])
  end

  def new
    @shop = Shop.find(params[:shop_id])
    @shop_comment = @shop.shop_comments.new
  end

  def edit
    @shop = Shop.find(params[:shop_id])
    @shop_comment = ShopComment.find(params[:id])
  end

  def create
    @shop = Shop.find(params[:shop_id])
    @shop_comment = @shop.shop_comments.create(shop_comment_params)

    if @shop_comment.save
      redirect_to shop_path(@shop), notice: "Sweet. You added a shop detail."
    else
      render 'new'
    end
  end

  def update
    @shop = Shop.find(params[:shop_id])
    @shop_comment = ShopComment.find(params[:id])

    if @shop_comment.update(shop_comment_params)
      redirect_to shop_shop_comment_path(@shop, @shop_comment), notice: "Sweet, you updated a Detail."
    else
      render 'edit'
    end
  end

  def destroy
    @shop_comment = ShopComment.find(params[:id])
    @shop_comment.destroy
    redirect_to shop_path(@shop_comment.shop), alert: "Oh nos, you deleted a detail!"
  end

  private
    def shop_comment_params
      params.require(:shop_comment).permit(:heading, :body)
    end

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  # before_action :authenticate_user!

  def index
    @shops = Shop.all
    @placeholder_shop = "/images/shops/default.jpg"
  end

  def show
    @shop = Shop.find(params[:id])
    @placeholder_shop = "/images/shops/default.jpg"
    @placeholder_drink = "/images/drinks/default.jpg"
  end

  def new
    @shop = Shop.new
  end

  def edit
    @shop = Shop.find(params[:id])
  end

  def create
    @shop = Shop.new(shop_params)

    if @shop.save
      redirect_to @shop, notice: "A new shop was created."
    else
      render 'new'
    end
  end

  def update
    @shop = Shop.find(params[:id])

    if @shop.update(shop_params)
      redirect_to @shop, notice: "Sweet, you updated a shop."
    else
      render 'edit'
    end
  end

  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy
    redirect_to shops_path, alert: "You deleted a shop."
  end

  private
    def shop_params
      params.require(:shop).permit(:img_url, :name, :shop_type, :address)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/drinks/_form.html.erb
<div id="error_explanation">
  <% @drink.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
</div>

<%= form_for [@shop, @drink] do |f| %>
  <p>
    <%= f.label :name, 'Name of Drink' %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :img_url, 'Image URL' %><br>
    <%= f.text_field :img_url %>
  </p>

  <p>
    <%= f.label :kind_of_drink, 'Kind of Drink' %><br>
    <%= f.text_field :kind_of_drink %>
  </p>

  <p>
  <%= f.label :roast %><br>
  <%= f.select :roast, ['Light', 'Medium', 'Medium-Dark', 'Dark'], include_blank: "Select A Roast" %>
  </p>

  <p>
    <%= f.label :flavor %><br>
    <%= f.text_field :flavor %>
  </p>

  <p>
    <%= f.label :thoughts %><br>
    <%= f.text_area :thoughts %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/drinks/edit.html.erb
<h1>Edit Drink</h1>
<div class="form-block">
  <%= render 'form' %>

  <%= link_to 'Back', [@drink.shop], :class => 'fa fa-arrow-left' %>
</div>

app/views/drinks/new.html.erb
<h1>New Drink</h1>
<div class="form-block">
  <%= render 'form' %>

  <%= link_to 'Back', [@drink.shop], :class => 'fa fa-arrow-left' %>
</div>

app/views/drinks/show.html.erb
<h1><%= @drink.name %></h1>
<div id="nav-links">
  <%= link_to 'Back', [@drink.shop, @shop], :class => 'fa fa-arrow-left' %> <%= link_to 'Delete Coffee', [@drink.shop, @drink],
               method: :delete,
               :class => 'fa fa-trash-o' %> <%= link_to 'Edit Coffee', edit_shop_drink_path(@drink.shop, @drink), :class => 'fa fa-pencil-square-o' %>
</div>
<% if @drink.img_url == "" %>
<% @drink.img_url = @placeholder_drink %>
<% end %>
<img class="drink" src="<%= @drink.img_url %>">
<ul class="drink-details">
  <% if @drink.kind_of_drink != "" %>
    <li class="fa fa-heart"><strong>Type:</strong> <%= @drink.kind_of_drink %></li>
  <% end %>
  <% if @drink.roast.present? %>
     <li class="fa fa-coffee"><strong>Roast:</strong> <%= @drink.roast %></li>
  <% end %>
  <% if @drink.flavor.present? %>
    <li class="fa fa-spoon"><strong>Flavor:</strong> <%= @drink.flavor %></li>
  <% end %>
</ul>

<% if @drink.thoughts.present? %>
<div class="detail-page">
  <h2>Thoughts</h2>
  <p><%= @drink.thoughts %></p>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoffeeCheck</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body class="<%= controller.controller_name %>">
    <header>
      <div class="container">
        <h1 id="logo"><%= link_to 'coffeecheck', root_path %></h1>
        <nav>
          <%= link_to 'Shops', shops_path %>
          <% if user_signed_in? %>
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </nav>
      </div>
    </header>

    <div class="container">
        <div class="content">
        <% flash.each do |type, message| %>
            <p class="flash <%= type %>"><%= message %></p>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shop_comments/_form.html.erb
<div id="error_explanation">
  <% @shop_comment.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
</div>

<%= form_for [@shop, @shop_comment] do |f| %>
  <p>
    <%= f.label :heading, 'Title' %><br>
    <%= f.text_field :heading %>
  </p>

  <p>
    <%= f.label :body, 'Detail' %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/shop_comments/edit.html.erb
<h1>Edit Detail</h1>
<div class="form-block">
  <%= render 'form' %>

  <%= link_to 'Back', [@shop_comment.shop], :class => 'fa fa-arrow-left' %>
</div>

app/views/shop_comments/new.html.erb
<h1>New Detail</h1>
<div class="form-block">
  <%= render 'form' %>

  <%= link_to 'Back', [@shop_comment.shop], :class => 'fa fa-arrow-left' %>
</div>

app/views/shop_comments/show.html.erb
<h1><%= @shop_comment.heading %></h1>
<div id="nav-links">
  <%= link_to 'Back', [@shop_comment.shop, @shop], :class => 'fa fa-arrow-left' %> <%= link_to 'Delete Detail', [@shop_comment.shop, @shop_comment],
               method: :delete,
               :class => 'fa fa-trash-o' %> <%= link_to 'Edit Detail', edit_shop_shop_comment_path(@shop_comment.shop, @shop_comment), :class => 'fa fa-pencil-square-o' %>
</div>
<div class="detail-page">
<p><%= @shop_comment.body %></p>
</div>

app/views/shops/_form.html.erb
<div id="error_explanation">
  <% @shop.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
</div>

<%= form_for @shop do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </p>

  <p>
    <%= f.label :img_url, 'Image URL' %><br>
    <%= f.text_field :img_url %>
  </p>

  <p>
    <%= f.label :shop_type %><br>
    <%= f.select :shop_type, ['Chain', 'Hipster', 'Local'], include_blank: "Select A Type" %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/shops/edit.html.erb
<h1>Edit Shop</h1>
<div class="form-block">
  <%= render 'form' %>

  <%= link_to 'Back', shops_path, :class => 'fa fa-arrow-left' %>
</div>

app/views/shops/index.html.erb
<h1>Shops</h1>
<div id="nav-links">
  <%= link_to 'Add a shop', new_shop_path, :class => 'fa fa-plus-circle' %>
</div>
<div class="favorite-shops">
  <% @shops.sort { |a,b| a.name <=> b.name }.each do |shop| %>
  <div class="shop-grid">
    <p><%= link_to shop.name, shop_path(shop) %></p>
    <% if shop.img_url == "" %>
    <% shop.img_url = @placeholder_shop %>
    <% end %>
    <%= link_to (image_tag shop.img_url), shop_path(shop) %>
  </div>
  <% end %>
</div>

app/views/shops/new.html.erb
<h1>New Shop</h1>
<div class="form-block">
  <%= render 'form' %>

  <%= link_to 'Back', shops_path, :class => 'fa fa-arrow-left' %>
</div>

app/views/shops/show.html.erb
<h1><%= @shop.name %></h1>
<div id="nav-links">
  <%= link_to 'Back', shops_path, :class => 'fa fa-arrow-left' %> <%= link_to 'Delete Shop', shop_path(@shop),
                method: :delete,
                :class => 'fa fa-trash-o' %> <%= link_to 'Edit Shop', edit_shop_path(@shop), :class => 'fa fa-pencil-square-o' %> <%= link_to 'Add Coffee', new_shop_drink_path(@shop), :class => 'fa fa-plus-circle' %> <%= link_to 'Add a Detail', new_shop_shop_comment_path(@shop), :class => 'fa fa-comment' %>
</div>
  <% if @shop.img_url == "" %>
  <% @shop.img_url = @placeholder_shop %>
  <% end %>
  <img class="shop" src="<%= @shop.img_url %>">

  <ul>
    <% if @shop.shop_type.present? %>
    <li class="fa fa-bars"><strong>Type:</strong> <%= @shop.shop_type %></li>
    <% end %>
    <% if @shop.address.present? %>
    <li class="fa fa-map-marker"><strong>Address:</strong> <%= @shop.address %></li>
    <% end %>
  </ul>

  <% if @shop.shop_comments.present? %>
      <h2>Details</h2>
      <% @shop.shop_comments.each do |comment| %>
        <div class="detail">
          <h3><%= link_to comment.heading, shop_shop_comment_path(@shop, comment) %></h3>
          <p><%= comment.body %></p>
        </div>
      <% end %>
<% end %>

  <% if @shop.drinks.present? %>
    <div class="favorite-drinks">
      <h2>Favorite Drinks</h2>
      <% @shop.drinks.sort { |a,b| a.name <=> b.name }.each do |drink| %>
        <div class="drink-grid">
          <p><%= link_to drink.name, shop_drink_path(@shop, drink) %></p>
          <% if drink.img_url == "" %>
          <% drink.img_url = @placeholder_drink %>
          <% end %>
          <%= link_to (image_tag drink.img_url), shop_drink_path(@shop, drink) %>
        </div>
      <% end %>
    </div>
<% end %>

app/views/welcome/index.html.erb
<div class="banner">
  <div class="banner-text">
    <h2>Keep Track</h2>
    <h3>of where you</h3>
    <h2>Caffeinate</h2>
  </div>
</div>